app.py
from flask import render_template
from routes.admin import admin_B
from routes.user import B_user
from routes.posts import posts_B
from routes import app
from datetime import datetime

app.register_blueprint(admin_B)
app.register_blueprint(B_user)
app.register_blueprint(posts_B)

@app.errorhandler(404)
def not_found(e):
  return render_template("404.html")

@app.context_processor
def inject_now():
    return {'now': datetime.utcnow()}

if __name__ == '__main__':
    app.run(debug=True, host="0.0.0.0", port=8002)

routes/__init__.py
from flask import Flask
from utils.db import db
from flask_ckeditor import CKEditor

app = Flask(__name__)


app = Flask(__name__,static_url_path='', static_folder=r'../static')

app.template_folder = '../templates'
app.secret_key = "super secret key"
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///blog.db'

app.config['CKEDITOR_PKG_TYPE'] = 'standard'
ckeditor = CKEditor(app)

db.init_app(app)

routes/admin.py
from flask import render_template, request, redirect, url_for, Blueprint, flash, session
from utils.db import db
from datetime import datetime
from model.post import blogpost

admin_B = Blueprint("admin_B", __name__)


@admin_B.route("/admin")
def admin():
    session["track"] = "admin_B.admin"
    if "user" in session:
        uid = session["user_id"]
        posts = blogpost.query.filter_by(user_id=uid).all()
        return render_template("admin.html", posts=posts)
    flash("! Please login first !")
    return redirect(url_for("B_user.register", mode="login"))

routes/posts.py
from flask import render_template, request, redirect, url_for, Blueprint, flash, session
from utils.db import db
from datetime import datetime
from model.post import blogpost
from model.likes import likes as l

posts_B = Blueprint("posts_B", __name__)


# This returns posts after being selected on index or from admin page.
@posts_B.route("/post/<int:post_id>")
def post(post_id):
    post = blogpost.query.filter_by(id=post_id).one()
    try:
        likes = l.query.filter_by(post_id=post_id).one()
        amt = likes.like_amt
        return render_template("post.html", post=post, like=amt)
    except:
        return render_template("post.html", post=post, like=0)


# post adding route
@posts_B.route("/addpost")
def a_p():
    if "user" in session:
        return render_template("addpost.html")
    session["track"] = "posts_B.a_p"
    flash("! Please login first !")
    return redirect(url_for("B_user.register", mode="login"))


# sends post to database.
@posts_B.route("/ap", methods=["POST"])
def ap():
    title = request.form["title"]
    author = request.form["author"]
    content = request.form["ckeditor"]
    uid = session["user_id"]

    post = blogpost(
        title=title,
        author=author,
        content=content,
        date_posted=datetime.now(),
        updated=None,
        user_id=uid,
    )

    db.session.add(post)
    db.session.commit()

    return redirect(url_for("admin_B.admin"))


# Post editing route.
@posts_B.route("/edit/", methods=["POST", "GET"])
def edit():
    post_id = request.form["edit_id"]
    post_to_edit = blogpost.query.filter_by(id=post_id).one()
    return render_template("updatepost.html", post=post_to_edit)


# Updates/edits post
@posts_B.route("/update", methods=["POST"])
def update():
    post_id = request.form["edit_id"]
    title = request.form["title"]
    author = request.form["author"]
    content = request.form["content"]
    word = content.split()

    post = blogpost.query.filter_by(id=post_id).one()
    post.title = title
    post.author = author
    post.content = content
    post.updated = datetime.now()
    db.session.commit()
    flash("Edited successfully!!", "message-success")
    return redirect(url_for("admin_B.admin"))


# Delete post
@posts_B.route("/delete", methods=["POST"])
def delete():
    id = request.form["del_id"]
    post_to_del = blogpost.query.get_or_404(id)
    try:
        db.session.delete(post_to_del)
        db.session.commit()
        flash("Deleted successfully!!", "message-success")
    except:
        flash("something went wrong!!")
    return redirect(url_for("admin_B.admin"))


# Post Search
@posts_B.route("/search", methods=["GET", "POST"])
def search():
    search_value = request.form["search"]
    post_ids = []

    if "user" in session:
        user_i = session["user_id"]
        posts = blogpost.query.filter_by(user_id=user_i).all()
        for post in posts:
            if search_value.lower() in post.title.lower():
                post_ids.append(post.id)
        result = blogpost.query.filter(blogpost.id.in_(post_ids)).all()
        if not result:
            return render_template(
                "index.html", info=f'Nothing found for "{search_value}"', posts=result
            )
        return render_template("index.html", posts=result)

    posts = blogpost.query.all()
    for post in posts:
        if search_value.lower() in post.title.lower():
            post_ids.append(post.id)
    result = blogpost.query.filter(blogpost.id.in_(post_ids)).all()
    if not result:
        return render_template(
            "index.html", info=f'Nothing found for "{search_value}"', posts=result
        )
    return render_template("index.html", posts=result)


# sends likes to database.
@posts_B.route("/like", methods=["POST"])
def like():
    likes = int(request.form["likes"])
    postid = request.form["postid"]
    userid = session["user_id"]
    result = l.query.filter_by(post_id=postid, user_id=userid).all()
    try:
        if likes > 0:
            likes = likes - 1
            post_obj = l.query.filter_by(
                post_id=postid, user_id=userid, like_amt=likes
            ).one()
            post_obj.post_id = postid
            post_obj.user_id = userid
            post_obj.like_amt = likes
            db.session.commit()
            return post(postid)
        else:
            likes = likes + 1
            post_obj = l.query.filter_by(
                post_id=postid, user_id=userid, like_amt=likes
            ).one()
            post_obj.post_id = postid
            post_obj.user_id = userid
            post_obj.like_amt = likes
            db.session.commit()

            return post(postid)
    except:
        likes = likes + 1
        post_obj = l(post_id=postid, user_id=userid, like_amt=likes)
        db.session.add(post_obj)
        db.session.commit()

        return post(postid)

routes/user.py
from flask import render_template, request, redirect, url_for, Blueprint, session, flash
from werkzeug.security import check_password_hash
from utils.db import db
from model.user import user as user_data
from model.post import blogpost

B_user = Blueprint("B_user", __name__)


def users_count():
    total = 0
    userss = (user_data.query.order_by(user_data.user_id.desc())).all()
    for each in userss:
        if each.user_id > total:
            total = each.user_id

    return total


@B_user.route("/")
def index():
    db.create_all()
    posts = blogpost.query.all()
    return render_template("index.html", posts=posts)


@B_user.route("/register", methods=["POST", "GET"])
def register():
    if "user" in session:
        return redirect(url_for("B_user.index"))
    return render_template("sign_in.html")


@B_user.route("/signup", methods=["POST", "GET"])
def signup():
    if request.method == "POST":
        email = request.form["email"]
        name = request.form["name"]
        password = request.form["password"]

        user_id = 1 + users_count()
        users = user_data(email, password, user_id, name)

        db.session.add(users)
        db.session.commit()

        return redirect(url_for("B_user.signin"))

    return redirect(url_for("B_user.register", mode="signup"))


@B_user.route("/signin", methods=["POST", "GET"])
def signin():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        try:
            user = user_data.query.filter_by(email=email).first()
            if check_password_hash(user.pswd, password):
                session["user"] = user.name
                session["user_id"] = user.user_id
                if "track" in session:
                    return redirect(url_for(session["track"]))
                return redirect(url_for("B_user.index"))
            else:
                flash("Invalid credentials ")
                return redirect(url_for("B_user.register", mode="login"))
        except:
            flash("Invalid credentials ")
            return redirect(url_for("B_user.register", mode="login"))

    return redirect(url_for("B_user.register", mode="login"))


@B_user.route("/logout")
def logout():
    session.pop("user", None)
    session.pop("user_id", None)
    session.pop("message", None)
    session.pop("track", None)
    return redirect(url_for("B_user.index"))


@B_user.route("/contact")
def contact():
    return render_template("contact.html")

templates/add.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>Blog | Yogesh bhatt</title>
    <link rel="shortcut icon" type="image/png" href="./static/images/ok.png">
    <style>
      *, *:after, *:before {
	      box-sizing: border-box;
      }
    </style>
	
  </head> 
  <body >
    <!-- Navigation -->
      <div class="scroll-up-btn">
        <i class="fas fa-angle-up"></i>
    </div>
    <nav class="navbar">
      <div class="max-width">
          <div class="logo"><a href="/">Blo<span>g</span></a></div>
          <ul class="menu">
              <li><a href="#contact" class="menu-btn">Contact</a></li>
              <li><a href="https://yogeshbhatt.info.np" class="menu-btn">Portfolio</a></li>
          </ul>
          <div class="menu-btn">
              <i class="fas fa-bars"></i>
          </div>
      </div>
  </nav>
  <br><br><br>
  
    <!-- Page Header -->

    <!-- Main Content -->
    <div class="container">
      <div class="card">
        <div class="card-image"></div>
          <form class="card-form" name="addForm" id="addForm" method="POST" action="{{ url_for('admin.addpost') }}" novalidate>
            <div class="input">
              <input type="text" class="input-field" placeholder="Title" name="title" id="title" required >
            </div>
            <div class="input">
              <input type="text" class="input-field" placeholder="Subtitle" name="subtitle" id="subtitle" required >
            </div>
            <div class="input">
              <input type="text" class="input-field" placeholder="Author" name="author" id="author" required >
            </div>
            <div class="input">
              <textarea rows="2" class="input-field" placeholder="Blog content" name="content" id="content" required ></textarea>
            </div>
            <div class="action">
              <button type="submit" class="action-button" id="sendMessageButton">Send</button>
            </div>
          </form>
      </div>
    </div>
    <hr>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
        {% for post in posts %}
          <div class="post-preview">
            <a href="{{ url_for('B_user.post', post_id=post.id) }}">
              <h2 class="post-title">
                {{ post.title }}
              </h2>
              <h3 class="post-subtitle">
                {{ post.subtitle }}
              </h3>
            </a>
            <p class="post-meta">Posted by {{ post.author }} on {{ post.date_posted.strftime('%B %d, %Y') }}</p>
            <form action="{{ url_for('admin.delete') }}" method="POST">
              <input type=hidden value="{{ post.id}}"name="del_id" id="del_id" />
              <button type="submit" onclick="myFunction()" class="action-button2" id="delete" action="">Delete</button>
            </form>
          </div>
          {% endfor %}
          <hr>
        </div>
      </div>
    </div>
    <!-- Footer -->
    <footer>
      <span>Created By <a href="http://yogeshbhatt.info.np">Yogesh Bhatt</a> | <span class="far fa-copyright"></span> 2020 All rights reserved.</span>
  </footer>
  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script>
      function myFunction() {
        document.getElementById("myForm").reset();
      }
      </script>
  </body>
</html>

templates/addpost.html
{% extends "base.html" %}
{% block content %}
{{ ckeditor.load() }}
<head>
    <title>Add post</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/poststyle.css') }}">
</head>


    <div class="add_container">
        <div class="blog-add">
            <div class="card">
            <div class="card-image"></div>
                <form class="card-form" name="addForm" id="addForm" method="POST" action="{{ url_for('posts_B.ap') }}" >
                    <div class="input">
                        <input type="text" class="input-field"  placeholder="Title" name="title" id="title" required>
                    </div>
                    <div class="input">
                        <input type="text" class="input-field" placeholder="Author" value="{{ session['user'] }}" name="author" id="author" required >
                    </div>
                    <div class="input">
                        {{ ckeditor.create() }}
                    </div>
                    <div class="action">
                        <button type="submit" class="action-button" id="sendMessageButton">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
{% endblock %}

templates/admin.html
{% extends "base.html" %}
{% block content %}

<head>
  <title>Admin</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/poststyle.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/flash.css') }}">
</head>
    <div class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
            <div class="message message-{{ category }}">
                <p>{{ message }}</p>
                <button class="close" onclick="this.parentElement.style.display='none';">&times;</button>
            </div>
            <script>
              setTimeout(function() {
                  document.querySelector('.message-{{ category }}').style.display = 'none';
              }, 3000);
          </script>
        {% endfor %}
      {% endif %}
      {% endwith %}
      <a href="{{ url_for('posts_B.a_p')}}">
        <button class="basic-button">Add post</button>
      </a>
      <a href="#">
        <button class="basic-button">Settings</button>
      </a>
      <br><br>
      <h3>Recent posts</h3>
      <hr>
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
        {% for post in posts[::-1] %}
          <div class="post-preview">
              <h2 class="post-title">
                {{ post.title }}
              </h2>
            <p class="post-meta">Posted on {{ post.date_posted.strftime('%B %d, %Y') }}</p>
            <div class="inner"> 
              <a href="{{ url_for('posts_B.post', post_id=post.id) }}" ><button  class="admin-button">View post</button></a>
              <form action="{{ url_for('posts_B.edit') }}" method="POST" style="display: inline-block;">
                <input type=hidden value="{{ post.id}}"name="edit_id" id="edit_id" />
                <button type="submit" onclick="myFunction()" id="edit" action="" class="admin-button">Edit</button>
              </form>
              <form action="{{ url_for('posts_B.delete') }}" method="POST" style="display: inline-block;">
                <input type=hidden value="{{ post.id}}"name="del_id" id="del_id" />
                <button type="submit" onclick="myFunction()" id="delete" action="" class="admin-button">Delete</button>
              </form>
            </div>
            <br>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='images/ok.png') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>

  </head> 
  <body >
      <div class="scroll-up-btn">
        <i class="fas fa-angle-up"></i>
      </div>
    <nav class="navbar">
        <div class="max-width">
            <div class="logo"><a href="/">Blo<span>g</span></a></div>
            <div class="search-form">
              <form action="{{ url_for('posts_B.search') }}" method="post">
                <input type="text" name="search" id="search" placeholder="Search for title">
                <button class="fa fa-search" type="submit"></button>
            </form>            
            </div>
            <ul class="menu">
              <li><a href={{ url_for('B_user.contact') }} class="menu-btn">Contact</a></li>
              <li><a href="https://yogeshbhatt.info.np" class="menu-btn">Portfolio</a></li>
              {%if "user" in session:%}
                <li><a href={{ url_for('admin_B.admin') }} class="menu-btn">{{ session['user'] }}</a></li>
                <li><a href={{ url_for('B_user.logout') }} class="menu-btn">Logout</a></li>
              {% else %}
                <li><a href={{ url_for('B_user.signin') }} class="menu-btn">Login</a></li>
              {% endif %}
            </ul>
            <div class="menu-btn">
                <i class="fas fa-bars"></i>
            </div>
        </div>
    </nav>
    <div class="main_content">
      {% block content %}
          {# Template inserted here #}
      {% endblock %}
    </div>
   <div class="footer">                                                                                           
      <span>Created By <a href="http://yogeshbhatt.info.np">SMR</a> | <span class="far fa-copyright"></span> {{ now.year }} All rights reserved.</span>
   </div>     
  </body>
  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
  
</html>

templates/contact.html
{% extends "base.html" %}
{% block content %}
<title>Contact me</title>
<!-- contact section start -->
      <section class="contact" id="contact">
        <div class="max-width">
            <h2 class="title">Contact me</h2>
            <div class="contact-content">
                <div class="column left">
                    <div class="icons">
                        <div class="row">
                            <i class="fas fa-user"></i>
                            <div class="info">
                                <div class="head">Name</div>
                                <div class="sub-title">Yogesh Bhatt</div>
                            </div>
                        </div>
                        <div class="row">
                            <i class="fas fa-map-marker-alt"></i>
                            <div class="info">
                                <div class="head">Address</div>
                                <div class="sub-title">Lahti 15200, Finland</div>
                            </div>
                        </div>
                        <div class="row">
                            <i class="fas fa-envelope"></i>
                            <div class="info">
                                <div class="head">Email</div>
                                <span><a style="color: #000000; text-decoration: none; font-size:20px; margin-left: 0px;" href="mailto:hello@yogeshbhatt.info.np">hello@yogeshbhatt.info.np</a></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
<head>
  <title>Blog | Yogesh bhatt</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/poststyle.css') }}">
</head>

<section class="post_list" id="post_list" >
<!-- Main Content -->
<div class="post_preview">
    <div class="max-width">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="text-1">{{info}}</div>
        {% for post in posts[::-1] %}
            <div class="post-card">
                <div class="blog-header">
                  <h2>{{ post.title }}</h2>
                    <p class="post-date">Posted by {{ post.author }} on {{ post.date_posted.strftime('%B %d, %Y') }}</p>
                </div>
                <div class="blog-content">
                  <p>{{ " ".join(post.content.split()[:14]) | safe }}...</p>
                  <br>
                  <a href="{{ url_for('posts_B.post', post_id=post.id) }}">
                    <button class="basic-button">Read More</button>
                  </a>
                </div>
            </div>
        {% endfor %}
      </div>
    </div>
</div>
</section>
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% block content %}
<head>
  <title>{{ post.title }}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/poststyle.css') }}">
</head>

<!-- Main Content -->
<section class="main_post" id="main_post">
  <div class="post">
    <button class="basic-button" onclick="goBack()">Back</button>
    <br>
    <br>
    <div class="blog-post">
      <div class="col-lg-8 col-md-10 mx-auto" >
        <h2>{{ post.title }}</h2>
        <p class="date-posted"> Posted by {{ post.author }} on {{ post.date_posted.strftime('%B %d, %Y') }}</p>
        <p>{{post.content|safe}}</p>
        <br>
        {%if "user" in session: %}
        <form action="{{ url_for('posts_B.like') }}" method="POST" style="display: inline-block;">
          <input type=hidden value="{{ post.id}}"name="postid" id="postid" />
          <input type=hidden value="{{ like}}"name="likes" id="likes" />
          <button type="submit" onclick="myFunction()" id="edit" action="" class="basic-button">Like ({{like}})</button>
        </form>
        {%else%}
        <button class="basic-button">Likes ({{like}})</button>
        {% endif%}
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/sign_in.html
<head>
  <meta charset="UTF-8">
  <title>Sign Up - Signin</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/loginstyle.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='images/ok.png') }}">

</head>
<body>
<!-- partial:index.partial.html -->
<html lang="en">
<head>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<nav class="navbar">
  <div class="max-width">
      <div class="logo"><a href="/">Blo<span>g</span></a></div>
      <ul class="menu">
        <li><a href={{ url_for('B_user.contact') }} class="menu-btn">Contact</a></li>
        <li><a href="https://yogeshbhatt.info.np" class="menu-btn">Portfolio</a></li>
      </ul>
      <div class="menu-btn">
          <i class="fas fa-bars"></i>
      </div>
  </div>
</nav>
<body>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    <center><h1>{{ message }}</h1></center>
    {% endfor %}
  {% endif %}
  {% endwith %}
<div id="form">
  <div class="container">
    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-md-8 col-md-offset-2">
      <div id="userform">
        <div class="tab-content">
          <div class="tab-pane fade {{ 'active in' if request.args.get('mode', 'signup') == 'signup' }}" id="signup">
            <h2 class="text-uppercase text-center"> Register </h2>
            <form id="signup" method="POST" action="{{ url_for('B_user.signup') }}">
              <div class="form-group">
                <label> Your Name<span class="req">*</span> </label>
                <input type="text" class="form-control" name="name" id="name" required data-validation-required-message="Please enter your name." autocomplete="off">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <label> Your Email<span class="req">*</span> </label>
                <input type="email" class="form-control" name="email" id="email" required data-validation-required-message="Please enter your email address." autocomplete="off">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <label> Password<span class="req">*</span> </label>
                <input type="password" class="form-control" name="password" id="password" required data-validation-required-message="Please enter your password" autocomplete="off">
                <p class="help-block text-danger"></p>
              </div>
              <div class="mrgn-30-top">
                <button type="submit" class="btn btn-larger btn-block">
                Sign up
                </button>
              </div>
            </form>
            <br>
            <p>Already have account?<a href="#login"  role="tab" data-toggle="tab"> Login here</a></p>
          </div>
          <div class="tab-pane fade {{ 'active in' if request.args.get('mode', '') == 'login' }}" id="login">
            <h2 class="text-uppercase text-center"> Log in</h2>
            <form id="login" method="POST" action="{{ url_for('B_user.signin') }}">
              <div class="form-group">
                <label> Your Email<span class="req">*</span> </label>
                <input type="email" class="form-control" name="email" id="email" required data-validation-required-message="Please enter your email address." autocomplete="off">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <label> Password<span class="req">*</span> </label>
                <input type="password" class="form-control" name="password" id="password" required data-validation-required-message="Please enter your password" autocomplete="off">
                <p class="help-block text-danger"></p>
              </div>
              <div class="mrgn-30-top">
                <button type="submit" class="btn btn-larger btn-block">
                Log in
                </button>
              </div>
            </form>
            <br>
            <p>Don't have account?<a href="#signup"  role="tab" data-toggle="tab"> Register here</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="footer">                                                                                           
  <span>Created By <a href="http://yogeshbhatt.info.np">SMR</a> | <span class="far fa-copyright"></span> {{ now.year }} All rights reserved.</span>
</div>  
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
<!-- partial -->
<script src="{{ url_for('static', filename='js/loginscript.js') }}"></script>

templates/updatepost.html
{% extends "base.html" %}
{% block content %}

<head>
    <title>Add post</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/poststyle.css') }}">
</head>
    <div class="add_container">
        <div class="blog-add">
            <div class="card">
            <div class="card-image"></div>
                <form class="card-form" name="addForm" id="addForm" method="POST" action="{{ url_for('posts_B.update') }}" >
                    <div class="input">
                        <input type="text" class="input-field" value="{{ post.title }}" placeholder="Title" name="title" id="title" required> 
                    </div>
                    <div class="input">
                        <input type="text" class="input-field" placeholder="Author" value="{{ post.author }}" name="author" id="author" required >
                    </div>
                    <div class="input">
                        <textarea rows="8" class="input-field" value="" placeholder="Blog content" required name="content" id="content" >{{ post.content }}</textarea>
                    </div>
                    <div class="input">
                        <input type=hidden value="{{ post.id }}" name="edit_id" id="edit_id" ></input>
                    </div>
                    <div class="action">
                        <button type="submit" class="action-button" id="sendMessageButton">Update</button>
                    </div>
                </form>
                {{ ckeditor.load() }}
                {{ ckeditor.config(name='content') }}
            </div>
        </div>
    </div>
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
{% endblock %}